"""Terminal RAG assistant — talks to the FastAPI backend over HTTP.

Companion to the Streamlit UI: same contract, zero heavy deps
(stdlib ``urllib`` only). Run from anywhere:

    python frontend/cli.py            # API default http://127.0.0.1:8000
    RAG_API=http://10.0.0.5:8000 python frontend/cli.py

Quit with Ctrl-D / Ctrl+C.
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request

_API = os.environ.get("RAG_API", "http://127.0.0.1:8000")

BANNER = r"""
  ____  _   ___________      __    ____   ____  ____  __  ___
 |  _ \ / \ |__  / / ___|    / \   |  _ \ / ___||  _ \|  \/  |
 | |_) / _ \  / /  \___ \   / _ \  | |_) | |  _ | |_) | |\/| |
 |  _ < / ___ \/ /_   ___) | / ___ \ |  _ < | |_| ||  _ <| |  | |
 |_| \_/_/   \_\____|____/|_/   \_\_| \_\ \____||_| \_\_|  |_|

                    grounded answers · cited sources
"""


def _call(method: str, path: str, payload: dict | None = None, timeout: int = 240) -> tuple[int, dict]:
    url = f"{_API}{path}"
    body = json.dumps(payload or {}).encode("utf-8")
    req = urllib.request.Request(
        url, data=body, method=method, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        try:
            return exc.code, json.loads(exc.read().decode("utf-8"))
        except Exception:
            return exc.code, {"detail": str(exc)}


def _print_answer(body: dict) -> None:
    print("\n" + "=" * 74)
    print(re.sub(r"(?im)^\s*Sources:.*\n?", "", body.get("answer", "(no answer)")).strip())
    print("=" * 74)
    for i, src in enumerate(body.get("sources", []), 1):
        line = src.get("line") or src.get("chunk")
        print(f"  [{i}] `{src.get('doc')}:{line}` chunk {src.get('chunk')} (d={src.get('distance', 0):.2f})")
    print(f"  (generated by: {body.get('backend')})")
    print()


def main() -> None:
    print(BANNER)
    status, body = _call("GET", "/health")
    if status == 200:
        h = body
        print(
            f"[store] {h.get('n_documents')} documents · {h.get('n_chunks')} chunks · "
            f"LLM {'online' if h.get('llm_available') else 'offline'}\n"
        )
    else:
        print(f"[warn] backend not reachable at {_API}: {body}\n")
    print("Ask me anything about orders / returns / refunds / shipping. Ctrl-D to exit.\n")

    while True:
        try:
            question = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nbye.")
            return
        if not question or question.lower() in {"quit", "exit", "q"}:
            print("bye.")
            return
        status, body = _call("POST", "/query", {"question": question})
        if status == 200:
            _print_answer(body)
        else:
            detail = body.get("detail", body)
            print(f"\n[error {status}] {detail}\n")


if __name__ == "__main__":
    main()
